[features]
seeds = false
skip-lint = false
[programs.devnet]
mysolanaapp = "8EYBEPrSifDH5widDTynxRqWqD6guqXFXSsDK4LxTYCm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"